name: Factory
version: '1.0-Factory'
main: org.factory.factory.Factory
api-version: '1.21'

softdepend: [ProtocolLib]

commands:
  factoryutils:
  refundmachine:
  shop:
  spawn:
  sellall:
  sellgui:
  catalog:
  multiblock:
  warp:
  profile:
  hazmat:
  rewards:
  abandonquest:
  quest:
